[CAST-208] Create GeoIP Analysis in CAST Backend
corshatech/cast pull request #105
Opened 2023-09-28 21:35 UTC by justincorsha

Before you submit your PR, make sure you check each of the following:

1. [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [x] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [x] I have **tested** my change / code and am confident that it works
4. [x] I have filled in the template below completely and accurately
##### Changelog

- Added make target to validate helm configuration
- Added geolocation to `init.sql` using [Maxmind's documentation](https://dev.maxmind.com/geoip/importing-databases/postgresql)
- Created secret to store script that will enable the PostGIS extension in the bitnami PostgreSQL instance
- Added query for finding geographic information from IPs in the `matview_traffic_ips` materialized view
- Handled data from query, removing duplicates and finding a maximum distance between requests, including a total error using the sum of errors from each point
- Updated enablements route to include a check for geo location data
- Duplicated geoip-data route into new geo-location-data route to upload Maxmind location data
- Created new types for geoip/geo-location data

*Note*: The CAST Wiki will be updated with steps to upload Maxmind location data:
>Once the file is downloaded you can unzip it and ensure that it contains the GeoLite2-City-Blocks-IPv4.csv and GeoLite2-City-Locations-en.csv files. CAST does not have UI for updating or uploading these files yet, but you can use cURL to upload the files on our current development branch:
>```bash
>curl -X POST localhost:3000/api/upload/geoip-data -F geoip_file=@/path/to/GeoLite2-City-Blocks-IPv4.csv
>curl -X POST localhost:3000/api/upload/geo-location-data -F geo_location_file=@/path/to/GeoLite2-City-Locations-en.csv
>```

##### Testing

- Added test data and checked that geo ip data is returned in reused auth analysis and includes the correct geo ip information as well as distances and errors

##### Unit Tests

N/A

2023-10-04 19:24 UTC, katieatcorsha reviewed
Very cool!

2023-10-04 19:24 UTC, katieatcorsha commented on ui/lib/analysis/reused-authentication.ts
> +) locations_with_max_distance ON false
Why "ON false"?

2023-10-05 19:05 UTC, ArcticLight requested changes

2023-10-05 19:05 UTC, ArcticLight commented on ui/lib/analysis/reused-authentication.ts
> +    );
This code works, but we should get together a little bit to see if we can't clean it up some

2023-10-05 21:04 UTC, justincorsha commented on ui/lib/analysis/reused-authentication.ts
> +		WHERE data->'request'->'headers'->>'Authorization' = ANY($1)
The `$1` is the array of secrets we get back from the first query. This allows us to filter the geoip/request data only on requests that share the same secrets in order to do less processing in the next step where we create pairs to find distances.

2023-10-05 21:09 UTC, justincorsha commented on ui/lib/analysis/reused-authentication.ts
> +) locations_with_max_distance ON false
We want to return both the information of the maximums as well as the requests themselves, so we join the table with just request information with a table that has the maximum distance and error for a specific secret. We can use `ON false` to join the tables without merging any rows, since the maximum doesn't apply to any specific row.

2023-10-11 15:38 UTC, katieatcorsha approved these changes

2023-10-11 16:09 UTC, justincorsha commented on k8s/helm/cast/Chart.yaml
> +    version: ^12.1.3
As suggested by @ArcticLight, we want to change to use the latest major version instead of the latest patch version. We can use the `^` and specify a minimum version to allow all versions up to the next major version, as described by the [semver reference](https://github.com/Masterminds/semver#caret-range-comparisons-major) from the [helm dependencies documentation](https://helm.sh/docs/chart_best_practices/dependencies/).

2023-10-11 19:28 UTC, katieatcorsha approved these changes

2023-10-12 14:44 UTC, ArcticLight approved these changes
LGTM, thanks!

2023-10-12 14:44 UTC, merged