[CAST-208] Geo Location Data Upload
corshatech/cast pull request #106
Opened 2023-09-29 19:25 UTC by justincorsha

Before you submit your PR, make sure you check each of the following:

1. [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [x] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [x] I have **tested** my change / code and am confident that it works
4. [x] I have filled in the template below completely and accurately
##### Changelog

- Added make target to validate helm configuration
- Added geolocation to init.sql using [Maxmind's documentation](https://dev.maxmind.com/geoip/importing-databases/postgresql)
- Created secret to store script that will enable the PostGIS extension in the bitnami PostgreSQL instance
- Updated enablements route to include a check for geo location data
- Duplicated geoip-data route into new geo-location-data route to upload Maxmind location data

**Note**: The CAST Wiki will be updated with steps to upload Maxmind location data:

>Once the file is downloaded you can unzip it and ensure that it contains the GeoLite2-City-Blocks-IPv4.csv and GeoLite2-City-Locations-en.csv files. CAST does not have UI for updating or uploading these files yet, but you can use cURL to upload the files on our current development branch:
>
>curl -X POST localhost:3000/api/upload/geoip-data -F geoip_file=@/path/to/GeoLite2-City-Blocks-IPv4.csv
>curl -X POST localhost:3000/api/upload/geo-location-data -F geo_location_file=@/path/to/GeoLite2-City-Locations-en.csv

##### Testing

- Deployed CAST locally and checked that I was able to upload and delete data in the new table using the new route

##### Unit Tests

N/A

2023-09-29 20:20 UTC, katieatcorsha requested changes
Can you add more detail to your testing steps? They're too vague to be auditable right now.

2023-09-29 20:20 UTC, katieatcorsha commented on k8s/helm/cast/files/init.sql
> +-- Schemas provided by Maxmind:
Nit: remove whitespace at the end of this line

2023-09-29 20:20 UTC, katieatcorsha commented on k8s/helm/cast/templates/secrets.yaml
> +  init.sh: {{ b64enc "PGPASSWORD=$POSTGRES_POSTGRES_PASSWORD psql -U postgres cast -c 'create extension postgis;'" }}
Can you explain this a bit so I understand? Seems like this grabs the admin PostgreSQL password and encodes it, uses psql somehow, and then not sure what the end bit does.

2023-09-29 20:20 UTC, katieatcorsha commented on ui/pages/api/enablements.ts
> +const hasGeoIPDataQuery = `SELECT COUNT(*) > 0 as on FROM geo_ip_data;`;
Here and elsewhere, why say "as" and then not provide an alias value?

2023-09-29 20:20 UTC, katieatcorsha commented on ui/pages/api/enablements.ts
> +      (await conn.query(hasGeoIPDataQuery)).rows[0].on
What does the `.on` bit do?

2023-09-29 20:20 UTC, katieatcorsha commented on ui/pages/index.tsx
> +                  tooltipDisabled='No MaxMind GeoIP data has been found. Check the CAST Wiki for details.'
Could we add a link here and below for usability?

2023-09-29 21:49 UTC, justincorsha commented on k8s/helm/cast/templates/secrets.yaml
> +  init.sh: {{ b64enc "PGPASSWORD=$POSTGRES_POSTGRES_PASSWORD psql -U postgres cast -c 'create extension postgis;'" }}
Sure! So the command starts at the quotation, which sets the `PGPASSWORD` environment variable needed by the psql command. This is provided by the `POSTGRES_POSTGRES_PASSWORD` environment variable, which is set by the container. We then log into the `cast` database as the `postgres` user with this password and run the `create extension postgis;` query to enable the extension. This is all passed into the b64enc helm template command since helm secret data needs to be base64 encoded.

2023-09-29 21:51 UTC, justincorsha commented on ui/pages/api/enablements.ts
> +const hasGeoIPDataQuery = `SELECT COUNT(*) > 0 as on FROM geo_ip_data;`;
The alias value is `on` which we use later in the typescript to get the boolean value returned by the query of whether or not these tables have data.

2023-09-29 21:51 UTC, justincorsha commented on ui/pages/api/enablements.ts
> +      (await conn.query(hasGeoIPDataQuery)).rows[0].on
This is related to the [alias question](https://github.com/corshatech/cast/pull/106#discussion_r1341820217).

2023-10-02 13:55 UTC, katieatcorsha commented on ui/pages/api/enablements.ts
> +const hasGeoIPDataQuery = `SELECT COUNT(*) > 0 as on FROM geo_ip_data;`;
OH, missed that! Thanks, Justin!

2023-10-02 13:55 UTC, katieatcorsha commented on ui/pages/api/enablements.ts
> +      (await conn.query(hasGeoIPDataQuery)).rows[0].on
Thank you!

2023-10-02 17:31 UTC, ArcticLight requested changes

2023-10-02 17:31 UTC, ArcticLight commented on ui/pages/index.tsx
> +                >
The NextJS Link component [cannot contain external URLs](https://github.com/vercel/next.js/blob/deprecated-main/errors/invalid-href-passed.md) - you must use an `a` tag instead.

2023-10-02 20:53 UTC, justincorsha commented on ui/pages/index.tsx
> +                >
Great catch!

2023-10-03 15:34 UTC, ArcticLight approved these changes

2023-10-03 15:36 UTC, katieatcorsha approved these changes

2023-10-04 13:40 UTC, merged