[CAST-209] Display GeoIP Analysis in CAST Frontend
corshatech/cast pull request #111
Opened 2023-10-05 21:43 UTC by justincorsha

Before you submit your PR, make sure you check each of the following:

1. [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [ ] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [x] I have **tested** my change / code and am confident that it works
4. [x] I have filled in the template below completely and accurately
##### Changelog

- Updated ReusedAuthenticationCard to have a mui Table with collapsible rows that provide the location for each request for a given secret
- Updated the reused auth query to only return relevant data for the outer table
- Added URI, port and occurredAt to the LocationData schema to be provided as data to the inner tables
- Changed joins in geoip table to be left joins to allow for all requests to be populated in the inner table (including those will null location data such as local ips)

##### Testing

Deployed CAST with sample data from `generate-pipeline-data.sh` and saw that it was populated in the Reused Authentication table

https://github.com/corshatech/cast/assets/109618849/906e2990-947f-4614-9b3a-45c21c07028c

##### Unit Tests

N/A

2023-10-12 14:47 UTC, ArcticLight requested changes
Just the one nit, great job

2023-10-12 14:47 UTC, ArcticLight commented on ui/components/app/Analysis/ReusedAuthenticationCard.tsx
> +export const HIGH_SEVERITY_DISTANCE = 100;
Can these constants please be moved to `@/lib/findings`?

2023-10-12 18:58 UTC, ArcticLight requested changes

2023-10-12 20:23 UTC, JasonCorsha commented on ui/components/app/Analysis/ReusedAuthenticationCard.tsx
> +          <IconButton aria-label="expand row" onClick={() => setOpen(!open)}>
```suggestion
          <IconButton aria-label="expand row" onClick={() => setOpen((prev) => !prev)}>
```

2023-10-12 20:35 UTC, JasonCorsha approved these changes
LGTM

2023-10-12 21:15 UTC, ArcticLight requested changes

2023-10-12 21:15 UTC, ArcticLight commented on ui/lib/analysis/reused-authentication.ts
> +    severity: severity,
Nit: Prefer puns when possible for readability

```suggestion
    severity,
```

2023-10-13 14:49 UTC, ArcticLight approved these changes

2023-10-13 14:49 UTC, merged