[CAST-288] Implement UI for Regex Findings Engine
corshatech/cast pull request #121
Opened 2023-10-25 15:40 UTC by justincorsha

Before you submit your PR, make sure you check each of the following:

1. [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [ ] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [x] I have **tested** my change / code and am confident that it works
4. [x] I have filled in the template below completely and accurately
##### Changelog

- Removed pass_in_url specific analysis from collector (will be done inside url_regex)
- Updated json keys for regex findings in `meta`
- Updated finding descriptions
- Created RegexPatternCard from PassInUrlCard to accept a regex name as an Id
- Created `regex_pattern.ts` from `pass_in_url.ts` to return the relevant data for a specific finding from the meta field in the traffic table
- Updated types to add the finding information to `PatternFindings`

##### Testing

- Deployed using test data and ensured that all findings displayed with the correct title, description, weakness information and data

##### Unit Tests

Updated unit tests using code from PassInUrl and checked that they passed.

2023-11-07 15:05 UTC, ArcticLight requested changes

2023-11-07 15:05 UTC, ArcticLight commented on ui/lib/findings.ts
> +})
Please use MakeFinding instead, like the other definitions. If there is an issue sending data across the wire, the backend should focus on matching this type definition with what it is sending using `map()` to match the expected kind, rather than crafting a bespoke definition that doesn't match the Finding interface.

2023-11-07 15:05 UTC, ArcticLight commented on ui/lib/findings.ts
> +  description: z.string().optional().describe('A description of the finding'),
Please do not modify IFinding in this way; the description comes from the Analysis upper-level object.

2023-11-07 15:05 UTC, ArcticLight commented on ui/pages/index.tsx
> +                        )}
compute the href once as a `const` and use it twice, rather than repeating the ternary operation twice

2023-11-07 16:19 UTC, justincorsha commented on ui/lib/findings.ts
> +})
I think I just had the names mixed up here. I used makeFinding for `RegexPattern`, I'll make that switch.

2023-11-14 15:40 UTC, Fern-Corsha commented on ui/pages/index.tsx
> +                  const id = a.id === 'regex-pattern' ?
this ternary is evaluating `'regex-pattern'` which I assume will always be true

2023-11-14 18:35 UTC, Fern-Corsha approved these changes

2023-11-14 21:25 UTC, DavidCorsha approved these changes

2023-11-14 21:25 UTC, merged