Feat/sv demo
corshatech/cast pull request #122
Opened 2023-10-25 17:47 UTC by ArcticLight

Before you submit your PR, make sure you check each of the following:

1. [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [x] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [x] I have **tested** my change / code and am confident that it works
4. [x] I have filled in the template below completely and accurately

##### Changelog

- Implements new UI for the demo
- Bugfix CAST-278 shows the error banner when `/enablements` errors.
- Bugfix CAST-282 fixes a new-ui specific bug in one of the table components' CSS.

##### Testing

- This specific demo branch was successfully QA'd and demoed.

##### Unit Tests

New UI does not introduce new components that have unit tests.

2023-10-26 15:49 UTC, justincorsha requested changes

2023-10-26 15:49 UTC, justincorsha commented on ui/pages/index.tsx
>    const { data: analysesResponse, isLoading, error } = useSWR<AnalysesResponse>('/api/analyses');
```suggestion
  const { data: analysesResponse, isLoading, analysesError } = useSWR<AnalysesResponse>('/api/analyses');
  const { data: enablements, error: enablementsError } = useSWR('/api/enablements', TypedFetch(CASTFeaturesListing))
```

2023-10-26 15:49 UTC, justincorsha commented on ui/components/app/Analysis/core/index.tsx
> +    weaknessLink ? (
We may want to look into Prettier sooner rather than later to solve these whitespace issues. Also are these needed?

2023-10-26 15:49 UTC, justincorsha commented on ui/tailwind.config.js
> +        'corsha-blue-light': 'rgb(22,49,60)',
We could probably keep this to as hex to match the others. Where's the source of truth on these values?
```suggestion
        'corsha-blue-light': '#16313C',
```

2023-10-27 14:49 UTC, ArcticLight commented on ui/tailwind.config.js
> +        'corsha-blue-light': 'rgb(22,49,60)',
RGB and the hex code actually do appear to have differences in practice (at least in my testing environment, Firefox on Mac). Settling on RGB(22,49,60) was an _incredibly_ painful process trying to match a color from a PowerPoint template in code. The source of truth for this value is "This specific value, phrased in RGB, causes Mac's Digital Color Meter app to report the same color between the PowerPoint and the web page".

Things that did not work, listed here for completeness:
- Our actual brand color, which displays differently for some incredibly absurd reason I don't understand
- The same color specified as hex
- The actual sRGB value coming from Color Meter when waved over the powerpoint. No, really, try it. You write down the color that Color Meter says it is, and a _slightly different color_ gets rendered. It was driving me mad

2023-10-27 14:51 UTC, ArcticLight commented on ui/components/app/Analysis/core/index.tsx
> +    weaknessLink ? (
This was a line change that resulted from running Code's default formatter on this file. I can undo the change here if you feel strongly about it but honestly I don't think it matters.

There is a ticket on the backlog to introduce prettier, it hasn't been introduced yet.

2023-10-27 15:00 UTC, justincorsha commented on ui/components/app/Analysis/core/index.tsx
> +    weaknessLink ? (
No worries, once we get Prettier settled in I think it should be fine.

2023-10-27 15:13 UTC, justincorsha commented on ui/tailwind.config.js
> +        'corsha-blue-light': 'rgb(22,49,60)',
Looked more into it, is this used anywhere other than the design system page right now? In that case we could probably come back to this since we've discussed that changes may need to be made there as well.

2023-10-27 16:35 UTC, justincorsha approved these changes
LGTM

2023-10-27 16:44 UTC, DavidCorsha requested changes

2023-10-27 16:44 UTC, DavidCorsha commented on ui/components/app/Analysis/core/index.tsx
> +          /* TODO: Dirty hacks */
Can we link a bug ticket instead of including a TODO?

2023-10-27 16:52 UTC, ArcticLight commented on ui/components/app/Analysis/core/index.tsx
> +          /* TODO: Dirty hacks */
This will get resolved with the removal of Material UI entirely, which is on the roadmap. There isn't a bug ticket for this as the issue is in MUI's theming system

2023-10-27 18:36 UTC, DavidCorsha commented on ui/components/app/Analysis/core/index.tsx
> +          /* TODO: Dirty hacks */
Ok, could you put that explanation as the code comment?

2023-10-27 19:46 UTC, ArcticLight commented on ui/components/app/Analysis/core/index.tsx
> +          /* TODO: Dirty hacks */
Fixed to be a better technical comment in https://github.com/corshatech/cast/commit/6958965f0f7d29821ced9df1850e8545346abbb0

Does this work for you?

2023-10-27 20:20 UTC, DavidCorsha approved these changes
Thank you!

2023-10-28 01:27 UTC, merged