CAST-197: Group Jenkins users by email domain
corshatech/cast pull request #136
Opened 2023-11-06 20:23 UTC by katieatcorsha

1. [X] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [X] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [X] I have **tested** my change / code and am confident that it works
4. [X] I have filled in the template below completely and accurately

##### Changelog

**`plugins/jenkins/main.go`**:
- List users from the configured Jenkins instance grouped by email domain. Print the number of domains and the number of total users.

**`plugins/jenkins/user.go`**:
- Add user struct to hold only the data we currently care about.
- Add functionality for iterating over a user's properties to find their email address.
- Add functionality to convert the Jenkins user data JSON blob into a list of users containing only the info we care about.

**`plugins/jenkins/connection.go`**:
- Jenkins instance configured connection can either list all users or list users grouped by email domain.

**`plugins/jenkins/connection_test.go`**:
- Unit test logic to group a list of users by email domain.
  - Ensure that users with missing email address are not included.
  - Ensure that users with invalid email address are not included.
  - Ensure users from separate, valid email domains are grouped correctly by domain.

##### Testing

Old and new unit tests pass:
```
cast % go test ./plugins/jenkins/...                     
ok  	github.com/corshatech/cast/plugins/jenkins	0.257s
```

Here is the new test showing the warning logs for the misconfigured users as well:
```
=== RUN   TestGroupByEmailDomain
time="2023-11-06T15:07:50-05:00" level=warning msg="No email address set for this user" user.FullName="Test User Missing Email" user.ID=test-no-email
time="2023-11-06T15:07:50-05:00" level=warning msg="Invalid email address for this user: \"nonsense-no-at-domain.com\"" user.FullName="Test User Invalid Email" user.ID=test-bad-email
--- PASS: TestGroupByEmailDomain (0.00s)
```

I also tested the Jenkins plugin manually:

1. I signed into our Jenkins instance and hit this endpoint in my browser while authenticated: `<jenkins_tld>/asynchPeople/api/json`
2. I opened the browser console, went to the Networking tab, inspected the requests made to Jenkins, and extracted my session ID (of the format "JSESSIONID.<something>=<something_else>.node0").
3. I ran CAST's Jenkins plugin with the session ID env variable set: `JENKINS_TLD="<jenkins_tld>" JENKINS_SESSION_ID=JSESSIONID.<redacted>=<redacted>.node0 go run ./plugins/jenkins`
4. I observed the logs in my terminal to ensure I successfully fetched the Jenkins instance user data:
```
INFO[0000] Built URL for querying Jenkins user data      requestURL="<jenkins_tld>/asynchPeople/api/json?tree=users[lastChange,project[fullName,url],user[id,fullName,absoluteURL,property[_class,address]{,15}]]"
INFO[0000] Session ID cookie has been set up for the request! 
INFO[0000] For the domain "corsha.com", found 33 Jenkins user account(s) 
INFO[0000] For the domain "github.com", found 1 Jenkins user account(s) 
INFO[0000] For the domain "users.noreply.github.com", found 1 Jenkins user account(s) 
INFO[0000] For the domain "arcticlight.me", found 1 Jenkins user account(s) 
INFO[0000] Scan completed. Skipping writing results to CAST DB...  domainCount=4 userCount=36
INFO[0000] Done.
```

##### Unit Tests

See changelog for details.

2023-11-06 22:32 UTC, ArcticLight requested changes

2023-11-06 22:32 UTC, ArcticLight commented on plugins/jenkins/connection.go
> +		if len(parts) < 2 {
I hate to be That Guy, but the [email address spec is very silly](https://en.wikipedia.org/wiki/Email_address#Syntax) and there actually can be multiple `@` as long as it's quoted; in addition RFC 6530 enables UTF-8 which will be a bit of a hairball as well.

For handling here, I think it's best if we simply took "everything to the right of the _last_ `@` in the string, dropping a trailing `>` if it exists" to be the domain, and I think that should work more reliably. You may reject valid emails if doing this a different way.

2023-11-07 00:34 UTC, katieatcorsha commented on plugins/jenkins/connection.go
> +		if len(parts) < 2 {
Yeah that's why I checked for `< 2` as the error case and not `!= 2`. The email address is split on `@`, regardless of how many there are, and then the part to the right of the last `@` is taken as the domain. I can add the bit about dropping the trailing `>` though.

2023-11-07 14:51 UTC, DavidCorsha requested changes

2023-11-07 15:15 UTC, katieatcorsha commented on plugins/jenkins/connection.go
> +		if len(parts) < 2 {
Done!

2023-11-07 15:15 UTC, ArcticLight approved these changes

2023-11-07 15:23 UTC, katieatcorsha commented on plugins/jenkins/user.go
> +	var users []*User
I don't know why, but that consistently doesn't work for me. The list of users ends up with tons of nil values, which then cause panics from nil pointers.

2023-11-07 15:33 UTC, ArcticLight approved these changes

2023-11-07 15:34 UTC, DavidCorsha commented on plugins/jenkins/user.go
> +	var users []*User
When preallocating you will need to assign by slice index rather than using append.

2023-11-07 15:38 UTC, katieatcorsha commented on plugins/jenkins/user.go
> +	var users []*User
Welp that explains that! Will try again.

2023-11-07 15:43 UTC, katieatcorsha commented on plugins/jenkins/user.go
> +	var users []*User
Done.

2023-11-07 15:46 UTC, ArcticLight approved these changes

2023-11-07 15:48 UTC, DavidCorsha approved these changes

2023-11-07 15:49 UTC, merged