"UseOfBasicAuth" Finding
corshatech/cast pull request #17
Opened 2023-01-30 16:28 UTC by Russ-Corsha

Before you submit your PR, make sure you check each of the following:

1. [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [x] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [x] I have **tested** my change / code and am confident that it works
4. [x] I have filled in the template below completely and accurately

##### Changelog
Add in the "UseOfBasicAuth" Finding.  Added jest test to check the logic and added sql traffic to test the psql query. 

##### Testing
Used skaffold to set up the database, added traffic with basic auth, and ran my call against the db.

##### Unit Tests
Jest unit test: ui/src/__tests__/analysis/useOfBasicAuth.test.ts

2023-01-30 20:05 UTC, DavidCorsha requested changes

2023-01-31 14:59 UTC, Russ-Corsha commented on ui/package.json
> +		"test": "jest --watchAll",
watch wont trigger on tests that havent changed

2023-01-31 15:07 UTC, Russ-Corsha commented on scripts/cast-ui-local-dev-server.sh
> +PGUSER=postgres
yes, done

2023-01-31 18:04 UTC, DavidCorsha requested changes

2023-01-31 18:04 UTC, DavidCorsha commented on ui/src/__tests__/analysis/useOfBasicAuth.test.ts
> +/* Copyright 2022 Corsha.
```suggestion
/* Copyright 2023 Corsha.
```

2023-01-31 18:04 UTC, DavidCorsha commented on ui/src/lib/findings.ts
> +export type Proto = "tcp" | "udp" | "unknown";
Is this used elsewhere

2023-01-31 18:27 UTC, Russ-Corsha commented on ui/src/lib/findings.ts
> +export type Proto = "tcp" | "udp" | "unknown";
no, though it may be nice to add a `toProto(string)` method in the future.  removed

2023-01-31 18:28 UTC, DavidCorsha requested changes

2023-01-31 18:37 UTC, Russ-Corsha commented on ui/src/lib/analysis/useOfBasicAuth.ts
> +    title: "Reused Authentication",
Great catch, changed

2023-01-31 18:38 UTC, DavidCorsha approved these changes

2023-01-31 18:41 UTC, merged