Implement the urlpassword analysis
corshatech/cast pull request #23
Opened 2023-01-31 17:53 UTC by ericatcorsha

Before you submit your PR, make sure you check each of the following:

1. [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [x] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [x] I have **tested** my change / code and am confident that it works
4. [x] I have filled in the template below completely and accurately
##### Changelog

- implemented the pass-in-url analysis

2023-01-31 21:39 UTC, DavidCorsha requested changes

2023-01-31 21:39 UTC, DavidCorsha commented on collector/analysis/pass_in_url/pass_in_url.go
> +		_ = tx.Rollback()
Is this a common pattern, to attempt a rollback even if committing succeeds?

2023-01-31 21:39 UTC, DavidCorsha commented on collector/analysis/pass_in_url/pass_in_url.go
> +	result := []string{}
https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices

2023-01-31 21:39 UTC, DavidCorsha commented on ui/src/lib/analysis/pass_in_url.ts
> +/* Copyright 2022 Corsha.
```suggestion
/* Copyright 2023 Corsha.
```

2023-02-01 16:51 UTC, DavidCorsha approved these changes

2023-02-01 16:52 UTC, ArcticLight requested changes

2023-02-01 16:52 UTC, ArcticLight commented on ui/src/lib/analysis/pass_in_url.ts
> +    description: "Potential password in query string",
```suggestion
    description: "A password or credential was detected in a URL as a query parameter. Using secure transport like HTTPS does not resolve the issue, because the URL may become logged or leak to third parties through e.g. the Referrer header. Do not include credentials in any part of a URL.",
    weaknessLink: "https://owasp.org/www-community/vulnerabilities/Information_exposure_through_query_strings_in_url",
    weaknessTitle: "(OWASP) Information Exposure through Query Strings in URL",
```

2023-02-01 16:52 UTC, ArcticLight commented on ui/src/pages/api/analyses.ts
> +const analysisFunctions: AnalysisFunction[] = [reusedAuthentication, pass_in_url, useOfBasicAuth];
```suggestion
const analysisFunctions: AnalysisFunction[] = [reusedAuthentication, passInUrl, useOfBasicAuth];
```

2023-02-01 16:52 UTC, ArcticLight commented on sql/sample-data/traffic.sql
> +}');
This test traffic doesn't look like it would actually _trigger_ the password-in-url finding? Am I missing something?

2023-02-01 16:52 UTC, ArcticLight commented on ui/src/lib/analysis/pass_in_url.ts
> +        URI: row.uri,
No code appears to exist for sanitizing the URL/URI to not contain the detected password field, in any of the collector or backend. We should make an effort not to store or log what we suspect is a password

2023-02-02 14:41 UTC, ericatcorsha commented on ui/src/lib/analysis/pass_in_url.ts
> +        URI: row.uri,
It is now [removing the query string](https://github.com/corshatech/cast/pull/23/files#diff-587ed414062c5eac168651a3e16ef659e58f45462a89b42b118e5632e15ddf5fR27) when it detects passwords in the url, and the collector[ updates the traffic data's absoluteURI](https://github.com/corshatech/cast/pull/23/files#diff-bacda4196256b80bde6a1f6a6cc19d08e3309a4418a179ac4a730135bf950825R338) with the sanatized url

2023-02-02 14:46 UTC, ericatcorsha commented on sql/sample-data/traffic.sql
> +}');
At the moment the traffic data is only used for UI dev testing, so what you're seeing resembles what the collector inserts into the table. 

We may want to change the dev script so that it runs a JSON file of kubeshark messages through the collector so that it inserts the data into the database rather than inserting directly into the database.

2023-02-02 14:57 UTC, ericatcorsha commented on ui/src/lib/analysis/pass_in_url.ts
> +    description: "Potential password in query string",
[done](https://github.com/corshatech/cast/pull/23/files#diff-f246a45b66691129459dfeafd01ca380e3c6ccb4613d52bc832c460eeac62914R30-R35)

2023-02-02 14:58 UTC, ericatcorsha commented on ui/src/pages/api/analyses.ts
> +const analysisFunctions: AnalysisFunction[] = [reusedAuthentication, pass_in_url, useOfBasicAuth];
[done](https://github.com/corshatech/cast/pull/23/files#diff-5095cf412ec9ed6e6a4b9e54ec0ea266640ecac739b4d5ed54935c69656ef5aeR4)

2023-02-02 17:27 UTC, ArcticLight requested changes

2023-02-02 17:27 UTC, ArcticLight commented on collector/analysis/pass_in_url/pass_in_url.go
>  		if keys.Contains(strings.ToLower(k)) {
Test will never match e.g. `apiKey`, because strings is toLowered first; please lowercase your matching strings as well.

2023-02-02 17:57 UTC, ericatcorsha commented on collector/analysis/pass_in_url/pass_in_url.go
>  		if keys.Contains(strings.ToLower(k)) {
Ah, good catch, [fixed](https://github.com/corshatech/cast/pull/23/commits/bcbd62e8cc1013bfe33edbd14d7fd01378992a32)

2023-02-03 20:52 UTC, ArcticLight approved these changes

2023-02-06 00:56 UTC, DavidCorsha commented
@ericatcorsha now that we have merged a few analyses into main there are a few conflicts if you could help resolve those.

2023-02-07 15:36 UTC, ericatcorsha commented on ui/src/lib/analysis/pass_in_url.ts
> +    description: "Potential password in query string",
[done](https://github.com/corshatech/cast/pull/23/commits/330d6d40a2dffaf31052c4ba54f8fb8c35a05542)

2023-02-07 15:54 UTC, ArcticLight approved these changes

2023-02-07 16:08 UTC, merged