Output jwts to metadata
corshatech/cast pull request #27
Opened 2023-02-02 14:33 UTC by Priya-Corsha

Before you submit your PR, make sure you check each of the following:

1. [X] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [X] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [X] I have **tested** my change / code and am confident that it works
4. [X] I have filled in the template below completely and accurately
##### Changelog

> Added jwt detection to collector request processing to fill CASTMetadata with the result. Updated sample traffic and tests accordingly. 

##### Testing

> Ran CAST and confirmed the 'meta' column in the postgres database was filled and stored with detected jwts as expected.

##### Unit Tests

> Updated unit tests to include metadata.

2023-02-02 17:19 UTC, ArcticLight requested changes

2023-02-02 17:19 UTC, ArcticLight commented on collector/collector.go
> +func handleMessage(message []byte, msgStruct *Message) ([]byte, []byte, error) {
Can we add a doc comment explaining the inputs and outputs of this function? It isn't obvious anymore what the returns refer to.

2023-02-02 18:03 UTC, Priya-Corsha commented on collector/collector.go
> +func handleMessage(message []byte, msgStruct *Message) ([]byte, []byte, error) {
Added.

2023-02-03 20:51 UTC, ArcticLight approved these changes

2023-02-03 21:28 UTC, ArcticLight approved these changes

2023-02-03 21:28 UTC, merged