Linter workflow for pull requests
corshatech/cast pull request #3
Opened 2023-01-06 19:41 UTC by Priya-Corsha

1. [X] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [X] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [X] I have **tested** my change / code and am confident that it works
4. [X] I have filled in the template below completely and accurately
##### Changelog

> Added Linter workflow that lints Go code and helm charts on PR. 

##### Testing

> Triggered workflow with temporary push trigger and confirmed it lints as expected.

2023-01-12 21:27 UTC, ArcticLight requested changes

2023-01-12 21:27 UTC, ArcticLight commented on .github/linters/.stylelintrc.json
> +}
Same as above: can this be a _link_ to `ui/.stylelintrc` rather than a copy?

2023-01-12 21:27 UTC, ArcticLight commented on .github/pull_request_template.md
> +<!-- markdownlint-disable-file -->
Please disable the markdown linter project-wide, I don't think having one is a great plan.

2023-01-12 21:27 UTC, ArcticLight commented on CONTRIBUTING.md
> +* Project follows [Google JSON Style Guide](https://google.GitHub.io/styleguide/jsoncstyleguide.xml) for the REST APIs that are provided.
This is.... odd. Can it be changed back?

2023-01-12 21:27 UTC, ArcticLight commented on CONTRIBUTING.md
> +Pull requests must pass a [Super-Linter](https://github.com/github/super-linter) check before being merged. To run Super-Linter locally, use the command ```make super-linter```.
Can you mention that the super linter is run with `docker`? Something like
```suggestion
Pull requests must pass a [Super-Linter](https://github.com/github/super-linter) check before being merged.
If you would like to test your changes with the linter, we have a make script that runs Super-Linter locally using docker. You can use it with the command ```make super-linter```.
```

2023-01-12 21:27 UTC, ArcticLight commented on collector/collector.go
> +	websockertURLEnv = "WEBSOCKET_URL"
```suggestion
	websocketURLEnv = "WEBSOCKET_URL"
```

2023-01-12 21:27 UTC, ArcticLight commented on collector/collector.go
> +	websockertURL := requiredEnv(websockertURLEnv)
sp: websocket

2023-01-12 21:43 UTC, Priya-Corsha commented on .github/linters/.eslintrc.json
> +
Super-linter requires that custom config files be in the `/.github/linters` directory and could not find the config file when I used symlinks locally so no, I don't think so. We also use a javascript version of this file in `/ui/` while super-linter only takes yaml or json.

2023-01-12 21:44 UTC, Priya-Corsha commented on .github/workflows/release-helm.yml
> -          append_body: true
That parameter isn't used in the version we're running so I removed it.

2023-01-12 21:53 UTC, ArcticLight commented on .github/workflows/release-helm.yml
> -          append_body: true
👍

2023-01-12 22:01 UTC, ArcticLight commented on .github/linters/.eslintrc.json
> +
Fixed 👍

2023-01-12 22:20 UTC, Priya-Corsha commented on CONTRIBUTING.md
> +* Project follows [Google JSON Style Guide](https://google.GitHub.io/styleguide/jsoncstyleguide.xml) for the REST APIs that are provided.
Fixed.

2023-01-13 14:13 UTC, ArcticLight requested changes

2023-01-13 14:13 UTC, ArcticLight commented on ui/.eslintrc.js
> -  ],
I forgot to mention before, or I missed it: can you please make sure that these plugins are enabled in the eslint config? If you have trouble with the omni-linter with installing these, I can help you with it today

2023-01-13 14:13 UTC, ArcticLight commented on ui/.stylelintrc.js
> -  extends: ["stylelint-config-standard-scss", "stylelint-config-prettier-scss"],
Same as the above, let's make sure our extends still includes the same list as before

2023-01-18 09:01 UTC, ArcticLight approved these changes
lgtm

2023-01-18 13:44 UTC, merged