Feature: Password In URL Card
corshatech/cast pull request #37
Opened 2023-02-14 21:50 UTC by ArcticLight

Before you submit your PR, make sure you check each of the following:

1. [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [x] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [x] I have **tested** my change / code and am confident that it works
4. [x] I have filled in the template below completely and accurately
##### Changelog

- Create Pass In URL Card

##### Testing

- Snapshot-tested component and tried it with dummy data on the Dashboard

##### Unit Tests

- Snapshot test for component created based on dummy data

2023-02-14 21:51 UTC, ArcticLight commented on ui/components/app/Analysis/ReusedAuthentication.tsx
> -  GridValueGetterParams,
Removed unused import

2023-02-15 17:34 UTC, DavidCorsha requested changes

2023-02-15 17:34 UTC, DavidCorsha commented on ui/components/app/Analysis/PasswordInURLCard.tsx
> +        destIp,
Can we add destPort as well

2023-02-16 17:04 UTC, ArcticLight commented on ui/components/app/Analysis/PasswordInURLCard.tsx
> +        destIp,
Done

2023-02-17 15:27 UTC, DavidCorsha approved these changes

2023-02-17 16:02 UTC, merged