feat(STR-4442): update alignment in Analyses cards, Summary mobile st…
corshatech/cast pull request #47
Opened 2023-03-01 15:22 UTC by JasonCorsha

…yles

Before you submit your PR, make sure you check each of the following:

1. [X] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [X] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [X] I have **tested** my change / code and am confident that it works
4. [ ] I have filled in the template below completely and accurately
##### Changelog

> Briefly describe what you changed and in what files

##### Testing

> Briefly describe how you are sure your code works, and **be sure to include**:
> 1. what scenarios your testing covered,
> 2. any additional information that could help a reviewer, and
> 3. what updates may need to be made in downstream components, if any, to keep them working

##### Unit Tests

> Briefly describe your test coverage for your reviewer

2023-03-01 16:36 UTC, DavidCorsha requested changes

2023-03-01 16:36 UTC, DavidCorsha commented on ui/components/app/Analysis/core/CsvExportButton.tsx
> +        className="p-0 mb-[3px]"
Could you match the existing formatting in this file to keep the PR smaller?

2023-03-01 17:19 UTC, JasonCorsha commented on ui/components/app/Analysis/core/CsvExportButton.tsx
> +        className="p-0 mb-[3px]"
yeah, i'll go back and change the affected files. it's not just this one. no biggie

2023-03-02 17:33 UTC, ArcticLight requested changes

2023-03-02 17:33 UTC, ArcticLight commented on ui/components/app/Summary/index.tsx
> +        <Typography variant="h1" component="h1">
If this is using the new Typography, you should only need `variant="h1"` - the component should match automatically. Specifying component should only be necessary if the component needs to be overridden for some reason

2023-03-02 17:33 UTC, ArcticLight commented on ui/components/app/Summary/index.tsx
> +        ></Typography>
These should probably be divs, rather than empty Typography...?

2023-03-02 17:33 UTC, ArcticLight commented on ui/pages/index.tsx
> +    !isLoading &&
`isLoading` shouldn't be part of this check - it should just be `analysesResponse &&` due to how UseSWR works

2023-03-02 17:33 UTC, ArcticLight commented on ui/pages/index.tsx
> +              )}
We should make a note about fixing this behavior when `analyses.length === 0`. It's not within the scope of this work, but the skeleton version of the loading screen shouldn't appear when we have fully loaded _and_ no analyses were present. @DavidCorsha is that a new ticket or a todo comment?

2023-03-02 17:41 UTC, JasonCorsha commented on ui/pages/index.tsx
> +              )}
the UI should explain to the user that they didn't do anything wrong, and how to change their setup so they can see results, or if it's a good thing, tell them so.

2023-03-02 17:43 UTC, JasonCorsha commented on ui/components/app/Summary/index.tsx
> +        ></Typography>
yeah, those were already there when i started... i wasn't sure if it was intentional or not, but regardless i haven't touched the loading skin yet.

2023-03-03 14:55 UTC, DavidCorsha commented on ui/pages/index.tsx
> +              )}
@ArcticLight this would be a good new ticket

2023-03-06 18:47 UTC, closed without merging

2023-03-06 18:48 UTC, JasonCorsha commented
replaced by pull #48