CAST CLI
corshatech/cast pull request #51
Opened 2023-03-08 15:33 UTC by Priya-Corsha

Before you submit your PR, make sure you check each of the following:

1. [X] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [X] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [X] I have **tested** my change / code and am confident that it works
4. [X] I have filled in the template below completely and accurately
##### Changelog

> Added cast cli to run kubeshark tap and deploy cast with cast command. Updated README accordingly. 

##### Testing

> Built binary and confirmed cast -n <ns> started kubeshark tap of namespace and successfully deployed CAST with kubeconfig and kube-context as expected. 
 
> Confirmed CAST could install the kubeshark binary and use it if not found in $PATH.

2023-03-08 16:57 UTC, DavidCorsha requested changes

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +	uiPod := pods.Items[0]
Can you add a comment here explaining why we know that the first Item is correct?

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +		cancel()
Since this context is inherited it's better not to cancel it in this function. Instead we would want to return an error and let the context owner catch the error and perform cancellation as part of teardown in its defer statements. Better to return here anyway since it doesn't seem we can continue with the port forward if we failed to list pods.

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +	// download binary to config s directory
```suggestion
	// download binary to config directory
```

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +		log.Info("Error creating file to download kubeshark into.")
Add `WithError()`

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +		log.Infof("Error downloading release from %s", ksDownload)
Add `WithError()`

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +		log.Info("Error copying response into kubeshark file.")
Add `WithError()`

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +		return "", err
Add `WithError()`

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +		log.Info("Error creating private config directory.")
Add `WithError()`

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +	resp, err := http.Get(ksDownload) //#nosec
Is there a version of this Get call that can take a context parameter?

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +		println("Port forwarding is ready. CAST is available at http://localhost:3000/.")
Might be easier for terminals to hyperlink this if we remove the trailing dot
```suggestion
		println("Port forwarding is ready. CAST is available at http://localhost:3000/")
```

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +		browser.OpenURL("http://localhost:3000/") //nolint:errcheck
Just to keep our footprint smaller I would prefer not to use a new library to open their browser

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +		cancel()
Since we already defer cancel we could just log here that the signal was caught

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +			RepositoryConfig: "/tmp/.helmrepo",
Are these standard helm directories? If we are creating/owning them then it would be better to use the Go standard library functions to create temporary directories.

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +		log.WithError(err).Info("Error adding CAST helm repo.")
Seems better to log at the fatal level here, the cancel function should be called automatically as part of that teardown.

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +			log.WithError(err).Info("Error running kubeshark tap.")
Fatal level log?

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +	err := configdir.MakePath(configPath) // Ensure it exists.
It would be more polite to save the kubeshark binary to a temporary directory and clean that up when we are done so we don't create any new unexpected persistent files on the end-user systems.

2023-03-08 16:57 UTC, DavidCorsha commented on cmd/castRunner.go
> +func handleError(message string, err error, ctx context.Context) {
More consistent to keep the context argument first in every function signature.

2023-03-09 23:55 UTC, Priya-Corsha commented on Makefile
> +	$(GO) build -gcflags="all=-N -l" -o build/package/cast cast.go
Yes, we need to add a workflow for that.

2023-03-09 23:56 UTC, Priya-Corsha commented on README.md
> +      --kube-context string   Kube context to deploy CAST into.
Yes, it defaults to whatever the current context is. I added a default to the description to make it clearer.

2023-03-09 23:58 UTC, Priya-Corsha commented on cmd/castRunner.go
> +	err = clientset.CoreV1().Namespaces().Delete(context.TODO(), "cast", metav1.DeleteOptions{})
I had to use a new context here because the previous one had to be canceled before castCleanup was called to stop the resource creation in the deployCast goroutine.

2023-03-09 23:59 UTC, Priya-Corsha commented on cmd/castRunner.go
> +
The helm client deletes the stateful set so I believe the pvc gets deleted with it.

2023-03-10 00:00 UTC, Priya-Corsha commented on cmd/castRunner.go
> +// portForward port forwards from port 3000 on the pod to 3000 on localhost
Added.

2023-03-10 00:02 UTC, Priya-Corsha commented on cmd/castRunner.go
> +			RepositoryConfig: "/tmp/.helmrepo",
Those are the defaults used by the library. I could use the private config directory the kubeshark binary installs into instead to keep all the files in one place and/or delete the helm directories when the release is uninstalled. Would that work?

2023-03-10 00:04 UTC, Priya-Corsha commented on cmd/castRunner.go
> +	uiPod := pods.Items[0]
I couldn't create a scenario where a healthy deployment had multiple pods under that label so I switched to having it exit with an error if it finds more than one.

2023-03-10 13:38 UTC, DavidCorsha commented on cmd/castRunner.go
> +	err := configdir.MakePath(configPath) // Ensure it exists.
Spoke with @ArcticLight and this feature was his ask so let's keep it

2023-03-10 13:48 UTC, DavidCorsha commented on cmd/castRunner.go
> +			RepositoryConfig: "/tmp/.helmrepo",
The defaults are fine then, thanks!

2023-03-10 16:14 UTC, DavidCorsha requested changes

2023-03-10 20:33 UTC, DavidCorsha submitted a review, later dismissed

2023-03-10 20:34 UTC, ericatcorsha commented on README.md
> +./cast -n <namespace>
If this is the preferred way we want the public to install CAST, we should update TESTING.md so that QA testers will install CAST the way that the public would

2023-03-13 18:36 UTC, ericatcorsha requested changes

2023-03-13 18:36 UTC, ericatcorsha commented on README.md
> +./cast -n <namespace>
bump: we need to update TESTING.md with instructions to use the cast binary deploy cast

2023-03-14 15:47 UTC, ericatcorsha requested changes

2023-03-14 16:34 UTC, ericatcorsha approved these changes

2023-03-14 16:50 UTC, DavidCorsha commented
@ericatcorsha can you resolve the conversations if you approve?

2023-03-14 17:26 UTC, ericatcorsha commented
> @ericatcorsha can you resolve the conversations if you approve?

done

2023-03-14 18:04 UTC, ArcticLight approved these changes

2023-03-14 18:04 UTC, merged