Draft: Kubesec job k8s-hello-world
corshatech/cast pull request #56
Opened 2023-03-15 14:56 UTC by ArcticLight

Before you submit your PR, make sure you check each of the following:

1. [ ] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [ ] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [ ] I have **tested** my change / code and am confident that it works
4. [ ] I have filled in the template below completely and accurately
##### Changelog

> Briefly describe what you changed and in what files

##### Testing

> Briefly describe how you are sure your code works, and **be sure to include**:
> 1. what scenarios your testing covered,
> 2. any additional information that could help a reviewer, and
> 3. what updates may need to be made in downstream components, if any, to keep them working

##### Unit Tests

> Briefly describe your test coverage for your reviewer

2023-03-20 17:59 UTC, DavidCorsha requested changes

2023-03-20 17:59 UTC, DavidCorsha commented on plugins/kubesec/main.go
> +		log.WithError(err).Fatal("Couldn't construct K8s InClusterConfig")
```suggestion
		log.WithError(err).Fatal("Couldn't construct kubectl InClusterConfig")
```

2023-03-20 17:59 UTC, DavidCorsha commented on plugins/kubesec/cast_db.go
> +			time.Sleep(retryDelay)
Is this sleep redundant with the retry.Delay?

2023-03-20 17:59 UTC, DavidCorsha commented on plugins/kubesec/cast_db.go
> +			return err
Are there ever errors which should not retry?

2023-03-21 18:23 UTC, ArcticLight commented on k8s/helm/cast/templates/plugin-kubesec-cronjob.yaml
> +          containers:
Theoretically, but what do you want those limits to be?

2023-03-21 18:28 UTC, ArcticLight commented on plugins/kubesec/cast_db.go
> +	sqlStatement := `INSERT INTO plugins_completions (plugin_name) VALUES ($1)`
It's declared here as a variable at the top of the function. Do you mean to lift it into the global context at the top of the file? I'd rather have it nearer the use

2023-03-21 19:13 UTC, DavidCorsha commented on plugins/kubesec/main.go
> +		log.WithError(err).Fatal("Couldn't construct K8s InClusterConfig")
In-person discussion: Max says K8s is more accurate here

2023-03-22 16:12 UTC, ArcticLight commented on plugins/kubesec/cast_db.go
> +			return err
I'm not sure. I don't think so, but I'm not 100% certain. Could you give an example of such a scenario?

2023-03-22 16:16 UTC, DavidCorsha commented on plugins/kubesec/cast_db.go
> +	sqlStatement := `INSERT INTO plugins_completions (plugin_name) VALUES ($1)`
As a local constant is fine

2023-03-22 21:05 UTC, DavidCorsha commented on plugins/kubesec/cast_db.go
> +			time.Sleep(5 * time.Second)
If the Delay() isn't taking effect then it should be removed until we can figure out how to make use of it.

2023-03-22 21:15 UTC, DavidCorsha commented on k8s/helm/cast/templates/plugin-kubesec-cronjob.yaml
> +          containers:
Generally we set our limits by starting low (in the 100's of mVCPU) and increasing until we don't observe throttling in the Kubernetes Pod dashboard in Grafana.

2023-03-23 18:23 UTC, DavidCorsha commented on plugins/kubesec/cast_db.go
> +			return err
Ok, if we had a lot more retries than this it would be useful to only retry on connection-related error codes from `pq`

2023-03-23 18:32 UTC, DavidCorsha approved these changes

2023-03-23 18:51 UTC, DavidCorsha approved these changes

2023-03-23 18:55 UTC, merged