Draft implementation of the findings framework
corshatech/cast pull request #8
Opened 2023-01-13 22:07 UTC by ericatcorsha

Before you submit your PR, make sure you check each of the following:

1. [ ] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [ ] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [ ] I have **tested** my change / code and am confident that it works
4. [ ] I have filled in the template below completely and accurately
##### Changelog

> Briefly describe what you changed and in what files

##### Testing

> Briefly describe how you are sure your code works, and **be sure to include**:
> 1. what scenarios your testing covered,
> 2. any additional information that could help a reviewer, and
> 3. what updates may need to be made in downstream components, if any, to keep them working

##### Unit Tests

> Briefly describe your test coverage for your reviewer

2023-01-18 09:04 UTC, ArcticLight requested changes
Just two nits and we can get the definition here finalized

2023-01-18 09:04 UTC, ArcticLight commented on ui/src/lib/findings.ts
> +      string;
should probably be like this (?)
```suggestion
      /** The end date and time formatted as a UTC RFC-3339 string */
      end: string;
```

2023-01-18 09:04 UTC, ArcticLight commented on ui/src/lib/findings.ts
> +export type AnalysisFunction = () => Promise<Analysis>;
Doc comment doesn't describe exported type - this is the comment for the function below, perhaps?

2023-01-18 20:00 UTC, ericatcorsha commented on ui/src/lib/findings.ts
> +export type AnalysisFunction = () => Promise<Analysis>;
fixed

2023-01-18 20:07 UTC, ericatcorsha commented on ui/src/lib/findings.ts
> +      string;
fixed

2023-01-19 19:21 UTC, DavidCorsha requested changes

2023-01-19 19:21 UTC, DavidCorsha commented on ui/src/lib/findings.ts
> +/* Copyright 2022 Corsha.
2023 please

2023-01-23 14:38 UTC, ericatcorsha commented on ui/src/lib/findings.ts
> +/* Copyright 2022 Corsha.
done

2023-01-23 22:52 UTC, DavidCorsha approved these changes

2023-01-24 19:15 UTC, ArcticLight approved these changes

2023-01-24 21:45 UTC, DavidCorsha submitted a review, later dismissed

2023-01-30 18:06 UTC, DavidCorsha requested changes

2023-01-30 18:06 UTC, DavidCorsha commented on k8s/helm/cast/files/init.sql
> +CREATE INDEX IF NOT EXISTS idx_auth_header_src ON traffic USING BTREE (data->'request'->'headers'->>'Authorization', data->'src');
Should this be part of a separate PR?

2023-01-30 18:22 UTC, ericatcorsha commented on k8s/helm/cast/files/init.sql
> +CREATE INDEX IF NOT EXISTS idx_auth_header_src ON traffic USING BTREE (data->'request'->'headers'->>'Authorization', data->'src');
no, it is part of the reused authorization analysis. The index prevents a sequential scan of the table.

2023-01-30 18:26 UTC, DavidCorsha approved these changes

2023-01-30 18:35 UTC, ArcticLight approved these changes

2023-01-30 18:49 UTC, merged