[CAST-158] Implement Request Too Slow Detection
corshatech/cast pull request #83
Opened 2023-08-22 21:26 UTC by justincorsha

Before you submit your PR, make sure you check each of the following:

1. [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [x] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [x] I have **tested** my change / code and am confident that it works
4. [x] I have filled in the template below completely and accurately
##### Changelog

- Added Request Too Slow data generation to the `generate-pipeline-data.sh` script
- Created RequestTooSlowCard that populates a table with data from long-running requests
- Created request-too-slow endpoint that finds traffic data which is not a websocket or SSE and whose `elapsedTime` returned from kubeshark is longer than sixty seconds
- Fixed postgres indexes
- Fixed background color for cast ui

##### Testing

- Ran skaffold to use `generate-pipeline-data.sh` and checked that longer requests were populated in the table
- Sent requests that were long-running and checked that the correct data populated the table
- Sent requests that had attributes of SSE/websockets and checked that they were not added to the table

##### Unit Tests

- Added snapshot test for new RequestTooSlowCard
- Checked that unit tests passed

2023-08-24 18:43 UTC, ArcticLight requested changes

2023-08-24 18:43 UTC, ArcticLight commented on ui/components/app/Analysis/RequestTooSlowCard.tsx
> +    headerName: 'Elapsed Time (ms)',
Given that the minimum time for this to happen is in minutes, can this be displayed in units of least seconds?

Please display this value in the table (which may come from the backend in ms) in seconds as in `5010 (ms)` displayed as `5.01 (s)`

2023-08-24 18:43 UTC, ArcticLight commented on ui/lib/analysis/request_too_slow.ts
> +where elapsed_time > 60000 and method != 'CONNECT' and coalesce(connection_header, '') != 'Upgrade' and version = 'HTTP/1.1' and mimeType != 'text/event-stream' and not accept_header ~ 'text/event-st
Please extract 60000 as a constant and re-embed in the query, to make it clearer what this magic value is for and represents, as in:
```ts
/** Request Too Long maximum threshold, (ms) */
const ELAPSED_TOO_LONG_THRESHOLD = "60000";
// ...
`where elapsed_time > ${ELAPSED_TOO_LONG_THRESHOLD}`
```

2023-08-24 18:43 UTC, ArcticLight commented on ui/lib/analysis/request_too_slow.ts
> +      severity: row.elapsed_time > 180000 ? 'high' : 'medium',
Extract magic constant `180000` to top of file, same as the threshold value from the SQL query.

2023-08-24 18:43 UTC, ArcticLight commented on ui/lib/analysis/request_too_slow.ts
> +    severity: maxTime >= 180000 ? 'high' : 'medium',
Use the constant you extracted above, here.

2023-08-24 19:36 UTC, ArcticLight requested changes

2023-08-24 19:36 UTC, ArcticLight commented on ui/lib/analysis/request_too_slow.ts
> +  const maxTime = rows.length > 0 ? rows.reduce((prev, curr) => curr.elapsed_time > prev.elapsed_time ? curr : prev).elapsed_time : 0;
```suggestion
  const maxTime = (rows ?? []).reduce((prev, curr) => Math.max(prev, curr), 0)
```

2023-08-25 18:37 UTC, justincorsha commented on ui/lib/analysis/request_too_slow.ts
> +where elapsed_time > 60000 and method != 'CONNECT' and coalesce(connection_header, '') != 'Upgrade' and version = 'HTTP/1.1' and mimeType != 'text/event-stream' and not accept_header ~ 'text/event-st
Created `ELAPSED_MEDIUM_SEVERITY_THRESHOLD` variable set to 60 seconds.

2023-08-25 18:37 UTC, justincorsha commented on ui/lib/analysis/request_too_slow.ts
> +      severity: row.elapsed_time > 180000 ? 'high' : 'medium',
Created `ELAPSED_HIGH_SEVERITY_THRESHOLD` variable set to 60 seconds.

2023-09-06 17:04 UTC, JasonCorsha approved these changes
LGTM

2023-09-07 17:58 UTC, ArcticLight approved these changes

2023-09-07 17:58 UTC, merged