[CAST-154] Kubesec OWASP Unrestricted Resource Consumption
corshatech/cast pull request #93
Opened 2023-09-05 19:19 UTC by justincorsha

Before you submit your PR, make sure you check each of the following:

1. [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md) and signed the [Contributor License Agreement](./CLA.md).
2. [x] My code is clean and ready-to-PR, including being free of lint errors and dead code
3. [x] I have **tested** my change / code and am confident that it works
4. [x] I have filled in the template below completely and accurately
##### Changelog

- Duplicated KubesecFinding into KubesecResourcesFinding
- Created kubesec-resources analysis to look for Rule IDs relating to resource requests/limits
- Removed resource related findings from combined Kubesec table

##### Testing

- Deployed and checked that Rules with IDs `RequestsMemory`, `RequestsCPU`, `LimitsMemory`, `LimitsCPU` or `VolumeClaimRequestsStorage` appear in the new Kubesec Resources Finding table instead of the Kubesec table
 
![Screenshot 2023-09-05 at 2 25 17 PM](https://github.com/corshatech/cast/assets/109618849/c954a480-9694-4c68-b5fc-db3919224d66)

##### Unit Tests

Added snapshot test for KubesecCard

2023-09-06 17:16 UTC, JasonCorsha approved these changes
LGTM

2023-09-07 18:44 UTC, ArcticLight requested changes

2023-09-07 18:44 UTC, ArcticLight commented on ui/lib/analysis/kubesec-resources.ts
> +     data->>'Rule ID' IN ('${kubesecResourcesRules.join('\', \'')}')
This needs to be a parameterized query using a query builder, any time you're interpolating raw text.
I.e.:

```ts
// ...
findingsQuery = `
 data->>'Rule ID' IN $1
`;

// ...
const { rows } = await conn.query(query, [kubesecResourcesRules]);
```

It's much safer this way and you don't have to worry about implementing quoting correctly.
See: https://node-postgres.com/features/queries

2023-09-07 18:44 UTC, ArcticLight commented on ui/lib/analysis/kubesec-types.ts
> + ];
This should probably be moved from the types file (which is primarily concerned with Zod schemas) and into the kubesec analysis module instead, where this is used.

2023-09-07 18:44 UTC, ArcticLight commented on ui/lib/analysis/kubesec.ts
> +WHERE plugin_name = 'cast-kubesec' and not data->>'Rule ID' IN ('${kubesecResourcesRules.join('\', \'')}')
Same comment about using Query variables as above

2023-09-07 18:51 UTC, justincorsha commented on ui/lib/analysis/kubesec-resources.ts
> +     data->>'Rule ID' IN ('${kubesecResourcesRules.join('\', \'')}')
Great catch! This is a much cleaner solution too.

2023-09-08 21:05 UTC, ArcticLight approved these changes

2023-09-08 21:05 UTC, merged